return {

	COIN_ROLL_COSTS = {
		[1]  = 100,
		[5]  = 450,
		[10] = 800,
	},

	GEM_ROLL_COSTS = {
		[1]  = 50,
		[5]  = 225,
		[10] = 400,
	},

	PRODUCTS = {
		[100001] = { type = "gems",      amount = 500  },
		[100002] = { type = "gems",      amount = 1200 },
		[100003] = { type = "gems",      amount = 3000 },
		[100004] = { type = "gems",      amount = 7000 },
		[100005] = { type = "coinRolls", amount = 1   },
		[100006] = { type = "coinRolls", amount = 10  },
	},

	MAX_RECEIPT_LOG = 50,
}